CREATE TABLE IF NOT EXISTS daily_reports (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  patient_id               INTEGER NOT NULL,
  client_patient_id        TEXT,
  report_type              TEXT    NOT NULL CHECK(report_type IN ('morning','night')),
  bed_time                 TEXT,
  wake_time                TEXT,
  sleep_quality            TEXT,
  wake_ups                 INTEGER,
  felt_rested              INTEGER,
  meals_count              INTEGER,
  meals_note               TEXT,
  notes                    TEXT,
  updated_at               TEXT    NOT NULL DEFAULT (datetime('now')),
  edit_count               INTEGER NOT NULL DEFAULT 0,
  suspicious_edit_count    INTEGER NOT NULL DEFAULT 0,
  reliability_level        TEXT    NOT NULL DEFAULT 'High',
  crisis_level             TEXT    NOT NULL DEFAULT 'none',
  crisis_summary           TEXT,
  legacy_log_id            INTEGER UNIQUE,
  created_at               TEXT    NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (patient_id)    REFERENCES patients(id),
  FOREIGN KEY (legacy_log_id) REFERENCES logs(id)
);

CREATE INDEX IF NOT EXISTS idx_daily_reports_patient_id ON daily_reports(patient_id);
CREATE INDEX IF NOT EXISTS idx_daily_reports_created_at ON daily_reports(created_at);

CREATE TABLE IF NOT EXISTS weekly_screenings (
  id                              INTEGER PRIMARY KEY AUTOINCREMENT,
  patient_id                      INTEGER NOT NULL,
  client_patient_id               TEXT,
  wished_dead                     INTEGER NOT NULL DEFAULT 0,
  family_better_off_dead          INTEGER NOT NULL DEFAULT 0,
  thoughts_killing_self           INTEGER NOT NULL DEFAULT 0,
  thoughts_killing_self_frequency TEXT,
  ever_tried_to_kill_self         INTEGER NOT NULL DEFAULT 0,
  attempt_timing                  TEXT    NOT NULL DEFAULT 'none',
  current_thoughts                INTEGER,
  depressed_hard_to_function      INTEGER NOT NULL DEFAULT 0,
  depressed_frequency             TEXT,
  anxious_on_edge                 INTEGER NOT NULL DEFAULT 0,
  anxious_frequency               TEXT,
  hopeless                        INTEGER NOT NULL DEFAULT 0,
  could_not_enjoy_things          INTEGER NOT NULL DEFAULT 0,
  keeping_to_self                 INTEGER NOT NULL DEFAULT 0,
  more_irritable                  INTEGER NOT NULL DEFAULT 0,
  substance_use_more_than_usual   INTEGER NOT NULL DEFAULT 0,
  substance_use_frequency         TEXT,
  sleep_trouble                   INTEGER NOT NULL DEFAULT 0,
  sleep_trouble_frequency         TEXT,
  appetite_change                 INTEGER NOT NULL DEFAULT 0,
  appetite_change_direction       TEXT,
  support_person                  TEXT,
  reasons_for_living              TEXT,
  coping_plan                     TEXT,
  needs_help_staying_safe         INTEGER,
  updated_at                      TEXT    NOT NULL DEFAULT (datetime('now')),
  edit_count                      INTEGER NOT NULL DEFAULT 0,
  suspicious_edit_count           INTEGER NOT NULL DEFAULT 0,
  reliability_level               TEXT    NOT NULL DEFAULT 'High',
  crisis_level                    TEXT    NOT NULL DEFAULT 'none',
  crisis_summary                  TEXT,
  legacy_log_id                   INTEGER UNIQUE,
  created_at                      TEXT    NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (patient_id)    REFERENCES patients(id),
  FOREIGN KEY (legacy_log_id) REFERENCES logs(id)
);

CREATE INDEX IF NOT EXISTS idx_weekly_screenings_patient_id ON weekly_screenings(patient_id);
CREATE INDEX IF NOT EXISTS idx_weekly_screenings_created_at ON weekly_screenings(created_at);

INSERT OR IGNORE INTO daily_reports (
  patient_id,
  client_patient_id,
  report_type,
  bed_time,
  wake_time,
  sleep_quality,
  wake_ups,
  felt_rested,
  meals_count,
  meals_note,
  notes,
  updated_at,
  reliability_level,
  crisis_level,
  crisis_summary,
  legacy_log_id,
  created_at
)
SELECT
  logs.patient_id,
  json_extract(logs.value, '$.patientId'),
  CASE json_extract(logs.value, '$.reportType') WHEN 'night' THEN 'night' ELSE 'morning' END,
  json_extract(logs.value, '$.bedTime'),
  json_extract(logs.value, '$.wakeTime'),
  json_extract(logs.value, '$.sleepQuality'),
  json_extract(logs.value, '$.wakeUps'),
  CASE json_type(logs.value, '$.feltRested')
    WHEN 'true' THEN 1
    WHEN 'false' THEN 0
    ELSE json_extract(logs.value, '$.feltRested')
  END,
  json_extract(logs.value, '$.mealsCount'),
  json_extract(logs.value, '$.mealsNote'),
  COALESCE(json_extract(logs.value, '$.notes'), logs.note),
  logs.created_at,
  'High',
  'none',
  NULL,
  logs.id,
  logs.created_at
FROM logs
WHERE logs.type = 'sleep';

INSERT OR IGNORE INTO weekly_screenings (
  patient_id,
  client_patient_id,
  wished_dead,
  family_better_off_dead,
  thoughts_killing_self,
  thoughts_killing_self_frequency,
  ever_tried_to_kill_self,
  attempt_timing,
  current_thoughts,
  depressed_hard_to_function,
  depressed_frequency,
  anxious_on_edge,
  anxious_frequency,
  hopeless,
  could_not_enjoy_things,
  keeping_to_self,
  more_irritable,
  substance_use_more_than_usual,
  substance_use_frequency,
  sleep_trouble,
  sleep_trouble_frequency,
  appetite_change,
  appetite_change_direction,
  support_person,
  reasons_for_living,
  coping_plan,
  needs_help_staying_safe,
  updated_at,
  reliability_level,
  crisis_level,
  crisis_summary,
  legacy_log_id,
  created_at
)
SELECT
  logs.patient_id,
  json_extract(logs.value, '$.patientId'),
  COALESCE(json_extract(logs.value, '$.wishedDead'), 0),
  COALESCE(json_extract(logs.value, '$.familyBetterOffDead'), 0),
  COALESCE(json_extract(logs.value, '$.thoughtsKillingSelf'), 0),
  json_extract(logs.value, '$.thoughtsKillingSelfFrequency'),
  COALESCE(json_extract(logs.value, '$.everTriedToKillSelf'), 0),
  COALESCE(json_extract(logs.value, '$.attemptTiming'), 'none'),
  json_extract(logs.value, '$.currentThoughts'),
  COALESCE(json_extract(logs.value, '$.depressedHardToFunction'), 0),
  json_extract(logs.value, '$.depressedFrequency'),
  COALESCE(json_extract(logs.value, '$.anxiousOnEdge'), 0),
  json_extract(logs.value, '$.anxiousFrequency'),
  COALESCE(json_extract(logs.value, '$.hopeless'), 0),
  COALESCE(json_extract(logs.value, '$.couldNotEnjoyThings'), 0),
  COALESCE(json_extract(logs.value, '$.keepingToSelf'), 0),
  COALESCE(json_extract(logs.value, '$.moreIrritable'), 0),
  COALESCE(json_extract(logs.value, '$.substanceUseMoreThanUsual'), 0),
  json_extract(logs.value, '$.substanceUseFrequency'),
  COALESCE(json_extract(logs.value, '$.sleepTrouble'), 0),
  json_extract(logs.value, '$.sleepTroubleFrequency'),
  COALESCE(json_extract(logs.value, '$.appetiteChange'), 0),
  json_extract(logs.value, '$.appetiteChangeDirection'),
  json_extract(logs.value, '$.supportPerson'),
  COALESCE(json_extract(logs.value, '$.reasonsForLiving'), logs.note),
  json_extract(logs.value, '$.copingPlan'),
  json_extract(logs.value, '$.needsHelpStayingSafe'),
  logs.created_at,
  'High',
  'none',
  NULL,
  logs.id,
  logs.created_at
FROM logs
WHERE logs.type = 'weekly_check';
